version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: ansible_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password

    volumes:
      - ansible_db_data:/var/lib/mysql

  php:
    build:
      context: ./php
    container_name: ansible_php
    volumes:
      - ./html:/var/www/html
    depends_on:
      - db

  web:
    image: nginx:latest
    container_name: ansible_web
    ports:
      - "80:80"
    volumes:
      - ./html:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  adminer:
    image: adminer
    container_name: ansible_adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  ansible_db_data:
